### ISSUE TITLE
[ISSUE] Main Page Post Slide button 

### ISSUE THREAD

**Issue by gudcks0305** [GDSC-Daejin/gdsc-dju-blog-fe#37]
![image](https://user-images.githubusercontent.com/84506708/161941786-2cf9a8e3-6c2b-44c7-bf43-a3ea48bd3a2f.png)
3번째 버튼을 클릭하면 2번째로 버튼 표식이 가져 있고 
2번째 버튼은 첫번째로 버튼이 가 있습니다~

**Comment by bjc1102** [comment]
제 환경에서는 제대로 동작되긴 하는데 조금 수정해보고 다시 테스트 해볼게요
